name: "Release"
on:
  push:
    branches: [ develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      BAIDU_APPID: ${{ secrets.BAIDU_APPID }}
      BAIDU_APP_KEY: ${{ secrets.BAIDU_APP_KEY }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo BAIDU_APPID=${{ secrets.BAIDU_APPID }} >> .env
          echo BAIDU_APP_KEY=${{ secrets.BAIDU_APP_KEY }} >> .env

      - name: Setup Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Publish
        run: yarn run publish
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: medict-release-${{matrix.os}}-zip
          path: out/make/zip/darwin/x64/medict*
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Update Release
        # You may pin to the exact commit or the version.
        # uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: medict-${{matrix.os}}-${{ startsWith(github.ref, 'refs/tags/v') }}.zip
