#
# Copyright (C) 2023 Quan Chen <chenquan_act@163.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Node CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{matrix.os}}
    env:
      BAIDU_APPID: ${{ secrets.BAIDU_APPID }}
      BAIDU_APP_KEY: ${{ secrets.BAIDU_APP_KEY }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-10.15, ubuntu-latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo BAIDU_APPID=${{ secrets.BAIDU_APPID }} >> .env
          echo BAIDU_APP_KEY=${{ secrets.BAIDU_APP_KEY }} >> .env

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install

      - name: Test
        run: yarn run test